# How Requirements are Organized

Requirements are structured to provide a clear view of their definitions and parameters. Below is an outline detailing how these are organized, articulated through an example of a standard requirement.

## Requirement YZ-N-AAA Example

Each requirement has a unique ID, constructed as follows:

**YZ**: Sub-chapter numbers reflecting the requirement's area

**N**: Sequential number within the sub-chapter

**AAA**: The first three letters of the chapter topic

------------------------------------------------------------------------

**Description:** *X* of ***\[example parameter\]*** for measuring model uncertainty are implemented to provide a confidence interval for predictions in the app available at ***\[time point\]***.

## Parameters

| **Parameter**         | **Values**                                                                                       |
|------------------|------------------------------------------------------|
| **Example Parameter** | Parameters listed in brackets are adjustable by the WP 1 team during the project period.         |
| **Time Point**        | Refers to the deadline by which a requirement should be met, typically specifying some due date. |

## Phases

Each requirement is mapped to a specific project phase:

**Development**: Focuses on developing the tool's prototype until month 18.

**Testing**: The prototype undergoes testing until month 18.

**Validation**: Begins in month 18, marking the start of validating the developed and tested prototype.

## Stakeholders and Owner

**Stakeholders**: Includes project staff and other relevant groups affected by or necessary for fulfilling the requirement.

**Owner**: Each requirement is assigned an Owner, usually a WP lead relevant to existing tasks. The Owner is responsible for task delegation and execution to meet the requirement.

## Requirement Categorization

Based on the parameterized statements, requirements are classified into three sub-categories:

<div style="background-color:#abebc6; padding:10px; border-radius:5px;">

**Tolerable**: The minimum achievement threshold for a requirement.

</div>

<div style="background-color: #e8daef; padding:10px; border-radius:5px;">

**Goal**: Represents the objective aimed to be reached by the project. If both Tolerable and Goal are defined, the project's likely outcome will be between these two.

</div>

<div style="background-color:#e6f7ff; padding:10px; border-radius:5px;">

**Wish**: Desirable outcomes that are aimed for but likely only partially achieved.

</div>
