# 5 Diversity, non-discrimination, and fairness (DIV)

In order to achieve Trustworthy AI, we must enable inclusion and diversity throughout the entire AI system’s life cycle. Besides the consideration and involvement of all affected stakeholders throughout the process, this also entails ensuring equal access through inclusive design processes as well as equal treatment. This requirement is closely linked with the principle of fairness.

## Avoidance of unfair bias

Data sets used by AI systems (both for training and operation) may suffer from the inclusion of inadvertent historic bias, incompleteness and bad governance models. The continuation of such biases could lead to unintended (in)direct prejudice and discrimination against certain groups or people, potentially exacerbating prejudice and marginalisation. Harm can also result from the intentional exploitation of (consumer) biases or by engaging in unfair competition, such as the homogenisation of prices by means of collusion or a non-transparent market. Identifiable and discriminatory bias should be removed in the collection phase where possible. The way in which AI systems are developed (e.g. algorithms’ programming) may also suffer from unfair bias. This could be counteracted by putting in place oversight processes to analyse and address the system’s purpose, constraints, requirements and decisions in a clear and transparent manner. Moreover, hiring from diverse backgrounds, cultures and disciplines can ensure diversity of opinions and should be encouraged.

### Requirement 51-1-DIV {#51-1-div}

**Description:** Subgroup stratified according to ***features*** AND ***intersectional feature combination*** has prediction accuracy with no significant difference compared to the majority population.

***features***:

\- age

\- sex/gender

\- ethnicity/race

\- geographic location

***intersectional feature combination***:

\- sex/gender with ethnicity/race

**Phases**

\- development

\- testing

\- validation

**Owner**

\- WP 2 lead

**Stakeholders**

\- WP 2 (development)

**Goal**

\- Subgroup stratified according to ***age*** has prediction accuracy with no significant difference to the majority population.

\- Subgroup stratified according to ***sex/gender*** has prediction accuracy with no significant difference to the majority population.

\- Subgroup stratified according to ***ethnicity/race*** has prediction accuracy with no significant difference to the majority population.

\- Subgroup stratified according to ***geographic location*** has prediction accuracy with no significant difference to the majority population.

\- Subgroup stratified according to ***sex/gender and ethnicity/race*** has prediction accuracy with no significant difference to the majority population.

## Accessibility and Universal Design

Particularly in business-to-consumer domains, systems should be user-centric and designed in a way that allows all people to use AI products or services, regardless of their age, gender, abilities or characteristics. Accessibility to this technology for persons with disabilities, which are present in all societal groups, is of particular importance. AI systems should not have a one-size-fits-all approach and should consider Universal Design principles addressing the widest possible range of users, following relevant accessibility standards. This will enable equitable access and active participation of all people in existing and emerging computer-mediated human activities and with regard to assistive technologies.

### Requirement 52-1-DIV {#52-1-div}

**Description:** System undergoes UX/UI testing on ***X number user groups at time point***.

***X number***:

\- 6 to 8

***user groups***:

\- Stroke physicians of different technical skill levels

\- Stroke physicians of different medical skill levels

\- These user groups will later be updated when the User Groups for the Intended Purpose has been defined.

***time point***:

\- during demonstrator development and testing

**Phases**

\- development

\- testing

**Owner**

\- WP 3 lead

**Stakeholders**

\- WP 3 (design)

\- WP 4 (clinical validation)

**Tolerable**

\- System undergoes UX/UI testing on ***6-8 stroke physicians of different technical skill level during demonstrator development and testing***.

\- System undergoes UX/UI testing on ***6-8 stroke physicians of different medical skill level during demonstrator development and testing***.

## Stakeholder participation

In order to develop AI systems that are trustworthy, it is advisable to consult stakeholders who may directly or indirectly be affected by the system throughout its life cycle. It is beneficial to solicit regular feedback even after deployment and set up longer term mechanisms for stakeholder participation, for example by ensuring workers information, consultation and participation throughout the whole process of implementing AI systems at organisations.

### Requirement 53-1-DIV {#53-1-div}

**Description:** System is presented to X ***stakeholders*** for feedback ***time point***.

***stakeholders***:

\- Stroke patients and/or patient representatives from different geographical and cultural backgrounds

***time point***:

\- during demonstrator development and testing

**Phases**

\- development

\- testing

**Owner**

\- WP 3 lead

**Stakeholders**

\- WP 3 (design)

\- WP 6 (patient communication)

**Tolerable**

\- System is presented to ***4 stroke patients and/or patient representatives from different geographical and cultural backgrounds*** for feedback ***during demonstrator development and testing***.

**Goal**

\- System is presented to ***7 stroke patients and/or patient representatives from different geographical and cultural backgrounds*** for feedback ***during demonstrator development and testing***.

**Wish**

\- System is presented to ***10 stroke patients and/or patient representatives from different geographical and cultural backgrounds*** for feedback ***during demonstrator development and testing***.
