project:
  type: book

book:
  title: "VALIDATE Framework"
  author: ""
  date: ""
  chapters:
    - index.qmd
    - 0_organization.qmd
    - 1_hum.qmd
    - 2_rob.qmd  
    - 3_pri.qmd  
    - 4_tra.qmd  
    - 5_div.qmd  
    - 6_sus.qmd  
    - 7_acc.qmd  
    - wp_tasks.qmd  


format:
  html:
    theme: cosmo
    number-sections: false
  pdf:
    documentclass: scrreport
    mainfont: "Arial"
    sansfont: "Arial"
    include-before-body: "main.tex"
    include-in-header: 
      text: |
        \usepackage{scrlayer-scrpage}
        \clearpairofpagestyles
        \lofoot{VALIDATE}
        \rofoot{April 24}
        \usepackage{graphicx}
        \graphicspath{{images/}}
        \usepackage{wrapfig}
        \usepackage{blindtext}
        \usepackage{subfiles}
        \usepackage{multirow}
        \usepackage[table,xcdraw]{xcolor}